; This code is generated by Triops (in first person). If I have something to say, it'll be prepended with 'Triops'.
; Triops version: 0

global _start

section .text
_start:
	; Triops: Global variable intialization
	sub rsp, 32; Triops: This is the size of all variables on the stack
	mov qword [rsp + 0], greeting + 8; Triops: init `greeting`
	mov qword [rsp + 8], 11
	mov qword [rsp + 16], 0; Triops: init `var`

	; Triops: User code
	mov rax, 1
	mov rdi, 1
	mov rsi, qword [rsp + 0 + 0]
	mov rdx, qword [rsp + 0 + 8]
	syscall
	add qword [rsp + 16 + 0], 1

	; Triops: leaving the stack as I found it
	add rsp, 32; Triops: This was the size of all variables on the stack

	; Triops: Adding the unix exit, in case the user doesn't add one
	mov rax, 60; Triops: 60 is exit
	mov rdi, 0; Triops: 0 is success
	syscall

section .data
	greeting:
	dq 0
	db 72, 101, 119, 119, 111, 111, 32, 62, 46, 60, 10
